osx_image: xcode7.3
language: objective-c
podfile: Podfile
cache: cocoapods

script: set -o pipefail && xcodebuild -workspace 'UTF8CSV.xcworkspace' -scheme 'UTF8CSV' -configuration 'Debug' -sdk iphonesimulator -destination platform='iOS Simulator',OS='9.3',name='iPhone 6s' build test  | xcpretty -c --test
